import {scenarios} from './course.js';
import {digitalLevels,transmissionPath} from './model.js';
export const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,active=false,extra='')=>`<button type="button" data-action="${action}" class="${active?'selected':''}" aria-pressed="${active}" ${extra}>${text}</button>`;
const controls=(items,selected,action='mode')=>`<div class="segmented">${items.map(x=>button(x,action,x===selected,`data-value="${x}"`)).join('')}</div>`;
const device=(name,sub='')=>`<div class="device"><span class="device-screen" aria-hidden="true"></span><strong>${name}</strong>${sub?`<small>${sub}</small>`:''}</div>`;
function lane(direction='right',color='',label='Signal'){return `<div class="lane ${direction} ${color}" aria-label="${label}"><span class="lane-line"></span><span class="particle">${direction==='left'?'◀':'▶'}</span><span class="lane-label">${label}</span></div>`;}
export function pathDiagram(steps,active=-1){return `<div class="path-diagram">${steps.map((s,i)=>`${i?'<span class="path-arrow" aria-hidden="true">→</span>':''}<div class="path-node ${active===i?'lit':''}"><small>${String(i+1).padStart(2,'0')}</small><span>${s}</span></div>`).join('')}</div>`;}
export function waveSvg({bits=[1,0,1,1,0],type='digital',mode='Amplitude',value=1,bipolar=false}={}){
 let d='';const width=640,mid=100,step=width/bits.length;
 if(type==='digital') {digitalLevels(bits,bipolar).forEach((level,i)=>{const y=mid-level*58;d+=i===0?`M0 ${y}`:`V${y}`;d+=`H${(i+1)*step}`;});}
 else {for(let x=0;x<=width;x+=2){let amplitude=45,cycles=5,phase=0;if(type==='modulation'){if(mode==='Amplitude')amplitude=value?64:25;if(mode==='Frequency')cycles=value?10:4;if(mode==='Phase')phase=value?Math.PI:0;}if(type==='voice')amplitude=30+22*Math.sin(x/70);const y=mid-amplitude*Math.sin(x/width*Math.PI*2*cycles+phase);d+=`${x===0?'M':'L'}${x} ${y.toFixed(2)}`;}}
 const label=type==='digital'?`${bipolar?'Conceptual bipolar':'Unipolar'} signal for ${bits.join(' ')}`:`${type==='modulation'?mode+' for bit '+value:'Continuous analog'} waveform`;
 return `<svg class="wave" viewBox="-38 0 700 222" role="img" aria-label="${label}"><defs><pattern id="grid" width="32" height="25" patternUnits="userSpaceOnUse"><path d="M32 0H0V25" fill="none" stroke="currentColor" opacity=".09"/></pattern></defs><rect width="640" height="200" fill="url(#grid)"/><path d="M0 0V200M0 100H640" stroke="currentColor" opacity=".25"/><text x="-30" y="46">+</text><text x="-30" y="105">0</text><text x="-30" y="164">−</text><path class="signal-line" d="${d}"/><text x="580" y="220">Time</text>${type==='digital'?bits.map((b,i)=>`<text class="bit-label" x="${i*step+step/2}" y="192">${b}</text>`).join(''):''}</svg>`;
}
export function mountDemo(host,id){
 const state={mode:({circuit:'Physical circuit',configuration:'Point-to-point',flow:'Half-duplex',media:'Guided',wireless:'Radio',compare:'Analog',polarity:'Unipolar',modulation:'Amplitude'})[id],bits:[1,0,1,1,0],talk:'A',value:0,index:0,feedback:'',step:-1,data:'Digital',transmission:'Digital',medium:'Copper'};
 let timer;
 function render(){
 const oldFocus=host.contains(document.activeElement)?document.activeElement:null;
 const focusAction=oldFocus?.dataset.action;
 let html='';
 const bitButtons=()=>`<div class="bit-editor" aria-label="Editable binary data">${state.bits.map((b,i)=>`<button data-action="bit" data-index="${i}" aria-label="Bit ${i+1}: ${b}. Click to change" class="bit ${b?'one':''}">${b}</button>`).join('')}</div>`;
 if(id==='circuit')html=`${controls(['Physical circuit','Logical circuit'],state.mode)}<div class="connection ${state.mode==='Logical circuit'?'logical':''}">${device('Computer')} ${lane('right','','Communication')} ${device('Switch')}</div><div class="demo-caption"><strong>${state.mode}</strong><p>${state.mode==='Physical circuit'?'The solid path represents the actual cable connecting the devices.':'The highlighted communication uses the physical path. A logical circuit describes the connection and its transmission characteristics.'}</p></div>`;
 if(id==='configuration')html=`${controls(['Point-to-point','Multipoint'],state.mode)}<button class="diagram-button" data-action="explain" aria-label="Explain this circuit diagram">${state.mode==='Point-to-point'?`<div class="connection">${device('Computer A')}${lane('right','','Dedicated circuit')}${device('Computer B')}</div>`:`<div class="multipoint"><div class="device-stack">${['Device A','Device B','Device C'].map(n=>`<span>${n}</span>`).join('')}</div><div class="bus" aria-hidden="true"></div>${lane('right','','Shared communication path')}${device('Network')}</div>`}</button><p class="demo-caption" role="status">${state.feedback||'Click the diagram to find out who shares the path.'}</p>`;
 if(id==='flow')html=`${controls(['Simplex','Half-duplex','Full-duplex'],state.mode)}<div class="connection">${device('Device A',state.mode==='Half-duplex'?'Walkie-talkie A':state.mode==='Simplex'?'Sender':'Sender / receiver')}<div class="lanes">${state.mode==='Full-duplex'?lane('right','','A sends to B')+lane('left','teal','B sends to A'):lane(state.mode==='Half-duplex'&&state.talk==='B'?'left':'right','',state.mode==='Half-duplex'?`${state.talk} talks · ${state.talk==='A'?'B':'A'} listens`:'A sends · B receives')}</div>${device('Device B',state.mode==='Half-duplex'?'Walkie-talkie B':state.mode==='Simplex'?'Receiver':'Sender / receiver')}</div>${state.mode==='Half-duplex'?`<div class="segmented">${button('A Talks','talk',state.talk==='A','data-value="A"')}${button('B Talks','talk',state.talk==='B','data-value="B"')}</div>`:''}<p class="demo-caption" role="status">${state.mode==='Simplex'?'One direction only, like a traditional radio broadcast.':state.mode==='Full-duplex'?'Both lanes are active at once, like a telephone conversation.':`Only ${state.talk} is transmitting. The other device listens. Switching sending and receiving takes turnaround time.`}</p>`;
 if(id==='multiplexing')html=`<div class="multipoint mux"><div class="device-stack"><span>User A <b class="tag cyan">A</b></span><span>User B <b class="tag mint">B</b></span><span>User C <b class="tag amber">C</b></span></div><div class="bus"></div><div class="mux-box">Multiplexer</div><div class="mux-output"><span class="packet p1">A</span><span class="packet p2">B</span><span class="packet p3">C</span><small>High-speed physical circuit</small></div></div><div class="legend"><span><i class="cyan"></i>Logical communication A</span><span><i class="mint"></i>Logical communication B</span><span><i class="amber"></i>Logical communication C</span></div><p class="demo-caption">Follow the three colors into one higher-capacity path. This shows sharing conceptually, not a particular multiplexing technique.</p>`;
 if(id==='media')html=`${controls(['Guided','Wireless'],state.mode)}<div class="media-grid">${(state.mode==='Guided'?['Twisted-pair','Coaxial','Fiber-optic']:['Radio','Microwave','Satellite']).map((n,i)=>`<button class="medium-card ${state.chosen===n?'selected':''}" data-action="medium" data-value="${n}"><div class="medium-visual ${state.mode==='Guided'?'cable cable'+i:'air air'+i}" aria-hidden="true"><span></span><span></span><span></span></div><strong>${n}</strong></button>`).join('')}</div><p class="demo-caption" role="status">${state.feedback||'Select a medium to see how it fits into a circuit.'}</p>`;
 if(id==='wireless')html=`${controls(['Radio','Microwave','Satellite'],state.mode)}${state.mode==='Satellite'?`<div class="satellite-path"><div class="satellite-node">Satellite</div><div class="satellite-links"><span>↗</span><span>↘</span></div><div class="ground-stations">${device('Ground station A')}${device('Ground station B')}</div></div>`:`<div class="connection">${device(state.mode==='Radio'?'Laptop':'Building A')}<div class="air-path"><span class="air-pulse"></span><span class="air-pulse delay"></span><strong>${state.mode==='Radio'?'Radio through the air':'Directional microwave'}</strong><span class="direction">${state.mode==='Radio'?'◉  )))  ◉':'━━━━▶'}</span></div>${device(state.mode==='Radio'?'Wi-Fi access point':'Building B')}</div>`}<p class="demo-caption">${{Radio:'Radio carries signals through the wireless environment. Wi-Fi lets users stay connected while moving.',Microwave:'Directional transmission links locations without a cable between them.',Satellite:'Ground station A sends up to the satellite. The satellite relays the signal down to ground station B.'}[state.mode]}</p>`;
 if(id==='selection'){const s=scenarios[state.index];html=`<div class="scenario-counter">Scenario ${state.index+1} of ${scenarios.length}</div><h3>${s.title}</h3><p>${s.brief}</p><div class="choice-grid">${['Twisted-pair','Coaxial','Fiber-optic','Radio','Microwave','Satellite'].map(n=>button(n,'answer',state.chosen===n,`data-value="${n}"`)).join('')}</div><div class="feedback ${state.correct?'correct':''}" role="status">${state.feedback||'Choose the medium that best matches these requirements.'}</div><div class="actions"><button data-action="scenario-prev" ${state.index===0?'disabled':''}>Previous scenario</button><button data-action="scenario-next" ${state.index===scenarios.length-1?'disabled':''}>Next scenario</button></div>`;}
 if(id==='story3')html=`${pathDiagram(['Devices','Circuit','Point-to-point / Multipoint','Simplex / Half-duplex / Full-duplex','Communication medium','Destination'],state.step)}<button class="primary" data-action="trace">Trace the connection</button><p class="demo-caption" role="status">${state.step<0?'Follow each part of the connection.':['Start with the devices that need to communicate.','Provide a physical path and a logical communication connection.','Choose a dedicated two-device circuit or a shared circuit.','Decide whether communication is one-way, alternating or simultaneous.','Choose guided or wireless media for the requirements.','The signal reaches the destination.'][state.step]}</p>`;
 if(id==='hello')html=`<div class="hello-word">HELLO<span>information to send</span></div>${pathDiagram(['Data','Signal representation','Transmission medium','Receiver'],state.step)}<button class="primary" data-action="trace">Send HELLO</button><p class="demo-caption" role="status">${state.step<0?'The cable carries a signal that represents the word.':['Begin with the information: HELLO.','Represent that information using physical signal changes.','The medium carries those signal changes.','The receiver interprets the signal to recover the information.'][state.step]}</p>`;
 if(['digital','transmission','coding','polarity'].includes(id))html=`${id==='polarity'?controls(['Unipolar','Bipolar'],state.mode):''}<p class="demo-instruction">${id==='digital'?'Click a bit to switch between its two possible values.':'Change the bits and watch the corresponding signal states.'}</p>${bitButtons()}${id==='digital'?`<div class="binary-cells">${state.bits.map(b=>`<span class="${b?'on':''}">${b?'State 1':'State 0'}</span>`).join('')}</div>`:waveSvg({bits:state.bits,bipolar:state.mode==='Bipolar'})}${id==='transmission'?`<button class="primary" data-action="sendbits">Transmit bits</button><div class="transmit-bits" role="status">${state.step<0?'Ready to transmit':`Sending bit ${state.step+1}: ${state.bits[state.step]} → ${state.bits[state.step]?'high':'low'} signal`}</div>`:''}<p class="demo-caption">${id==='polarity'?(state.mode==='Bipolar'?'Illustrative bipolar mapping: 0 is zero; successive 1s alternate positive and negative. This is one example of polarity changes, not a definition of all bipolar coding.':'Simplified unipolar mapping: 0 is zero; 1 is a positive level.'):id==='digital'?'These five bits are a sample binary sequence, not the encoding of a particular word.':'Our agreed example: 0 → low signal; 1 → high signal. Both ends must use the same meaning.'}</p>`;
 if(id==='analog')html=`<div class="wave-wrap flowing">${waveSvg({type:'voice'})}</div><label class="slider-label" for="voice-level">Voice strength <input id="voice-level" type="range" min="30" max="100" value="${state.strength||100}"></label><p class="demo-caption">Move the control to change wave height. The waveform remains continuous.</p>`;
 if(id==='compare')html=`${controls(['Analog','Digital'],state.mode)}<div class="compare-grid"><div class="compare-card ${state.mode==='Analog'?'focused':''}"><h3>Analog</h3>${waveSvg({type:'analog'})}<p>Continuously changing values</p></div><div class="compare-card ${state.mode==='Digital'?'focused':''}"><h3>Digital</h3>${waveSvg({bits:state.bits})}<p>Discrete signal states</p></div></div><p class="demo-caption" role="status">${state.mode==='Analog'?'Follow the smooth curve: it passes through continuously changing values.':'Follow the steps: the signal uses distinct states.'}</p>`;
 if(['digitalpath','conversion','modem','voice'].includes(id)){
 const paths={digitalpath:['Computer','Digital data','Digital signal','Medium','Receiver'],conversion:['Digital data','Conversion','Analog signal'],modem:['Computer','Digital data','Modem: modulate','Analog signal','Modem: demodulate','Digital data','Computer'],voice:['Human voice','Analog sound','Codec: digital conversion','Digital network','Digital data received','Conversion to sound']};
 html=`${id==='modem'?'<div class="modem-equation"><b>MOD</b>ulator <span>+</span> <b>DEM</b>odulator <span>=</span> <strong>MODEM</strong></div>':''}${pathDiagram(paths[id],state.step)}${id==='conversion'||id==='modem'?`<div class="mini-wave">${waveSvg({type:(id==='conversion'?state.step>=2:state.step>=2&&state.step<=4)?'analog':'digital'})}</div>`:''}<button class="primary" data-action="trace">${id==='voice'?'Send a voice message':'Run transmission'}</button><p class="demo-caption" role="status">${state.step<0?'Run the animation to follow each stage.':`Stage ${state.step+1}: ${paths[id][state.step]}. ${id==='modem'&&state.step===4?'The receiving modem recovers the digital data.':id==='voice'&&state.step===2?'A codec translates analog voice into digital form.':''}`}</p>`;
 }
 if(id==='modulation')html=`${controls(['Amplitude','Frequency','Phase'],state.mode)}<div class="modulation-label"><span>Carrier represents bit</span>${button('0','carrier',state.value===0,'data-value="0"')}${button('1','carrier',state.value===1,'data-value="1"')}</div>${waveSvg({type:'modulation',mode:state.mode,value:state.value})}<p class="demo-caption" role="status">${{Amplitude:`Bit ${state.value}: ${state.value?'higher':'lower'} amplitude. The wave height changes.`,Frequency:`Bit ${state.value}: ${state.value?'more':'fewer'} cycles in the same time. The repetition rate changes.`,Phase:`Bit ${state.value}: ${state.value?'shifted':'original'} cycle position. The height and repetition rate stay the same.`}[state.mode]} These are illustrative mappings.</p>`;
 if(id==='simulator'){const result=transmissionPath(state.data,state.transmission,state.medium);html=`<div class="sim-controls">${[['Data type','data',['Analog','Digital']],['Transmission type','transmission',['Analog','Digital']],['Medium','medium',['Copper','Fiber','Wireless']]].map(([label,key,options])=>`<label>${label}<select data-select="${key}">${options.map(o=>`<option ${state[key]===o?'selected':''}>${o}</option>`).join('')}</select></label>`).join('')}</div><div class="sim-result" role="status">${result.supported?`${pathDiagram(result.steps,state.step)}<p>${result.note}</p>`:`<div class="scope-note"><strong>Outside the examples in these notes</strong><p>${result.reason}</p><small>This does not mean the combination is impossible in real networks.</small></div>`}</div><button class="primary" data-action="trace" ${!result.supported?'disabled':''}>Run this transmission</button><p class="demo-caption">Copper includes the guided copper cable examples; fiber carries light. This is a conceptual path, not a network configuration tool.</p>`;}
 if(id==='digitalpath')html+=`<div class="bit-stream" aria-label="Binary information moving toward the receiver"><span>Digital data</span><div class="mux-output"><span class="packet p1">1</span><span class="packet p2">0</span><span class="packet p3">1</span></div><span>Receiver</span></div>`;
 host.innerHTML=html;
 const traceButton=host.querySelector('[data-action="trace"], [data-action="sendbits"]');
 if(traceButton&&document.body.classList.contains('paused'))traceButton.textContent='Next step (animations paused)';
 if(focusAction==='trace'||focusAction==='sendbits')host.querySelector(`[data-action="${focusAction}"]`)?.focus({preventScroll:true});
 }
 function trace(total){clearInterval(timer);if(document.body.classList.contains('paused')){state.step=(state.step+1)%total;render();return;}state.step=0;render();timer=setInterval(()=>{if(document.body.classList.contains('paused'))return;if(state.step>=total-1){clearInterval(timer);return;}state.step++;render();},1100);}
 host.addEventListener('click',click);
 host.addEventListener('change',change);
 host.addEventListener('input',input);
 function input(e){if(e.target.id==='voice-level'){state.strength=Number(e.target.value);host.querySelector('.signal-line').style.transform=`translateY(${100-state.strength}px) scaleY(${state.strength/100})`;}}
 function change(e){if(e.target.dataset.select){clearInterval(timer);state[e.target.dataset.select]=e.target.value;state.step=-1;render();host.querySelector(`[data-select="${e.target.dataset.select}"]`).focus();}}
 function click(e){const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;
 if(action==='mode'){state.mode=b.dataset.value;state.feedback='';state.chosen=null;}
 if(action==='talk')state.talk=b.dataset.value;
 if(action==='carrier')state.value=Number(b.dataset.value);
 if(action==='bit')state.bits[Number(b.dataset.index)]^=1;
 if(action==='explain')state.feedback=state.mode==='Point-to-point'?'Exactly two devices use this dedicated connection: Computer A and Computer B.':'Devices A, B and C share one path. They must coordinate how they use it.';
 if(action==='medium'){state.chosen=b.dataset.value;state.feedback=({'Twisted-pair':'Guided medium: an office computer may use twisted-pair Ethernet.','Coaxial':'Guided medium: signals follow a physical coaxial cable. Cable construction was covered in Week 2.','Fiber-optic':'Guided medium: fiber is an example for a high-capacity backbone.','Radio':'Wireless medium: useful for mobility or inconvenient cable installation.','Microwave':'Wireless medium: directional transmission between locations.','Satellite':'Wireless medium: a relay between ground stations over very large distances.'})[state.chosen];}
 if(action==='answer'){state.chosen=b.dataset.value;state.correct=scenarios[state.index].answers.includes(state.chosen);state.feedback=state.correct?'Correct ✓ '+scenarios[state.index].reason:'Try Again — '+scenarios[state.index].hint;}
 if(action.startsWith('scenario-')){state.index+=action==='scenario-next'?1:-1;state.feedback='';state.chosen=null;state.correct=false;}
 if(action==='trace'||action==='sendbits'){const count=action==='sendbits'?5:id==='simulator'?transmissionPath(state.data,state.transmission,state.medium).steps.length:({story3:6,hello:4,digitalpath:5,conversion:3,modem:7,voice:6})[id];trace(count);return;}
 render();const selector=`[data-action="${action}"]${b.dataset.value?`[data-value="${b.dataset.value}"]`:b.dataset.index?`[data-index="${b.dataset.index}"]`:''}`;host.querySelector(selector)?.focus({preventScroll:true});
 }
 render();return ()=>{clearInterval(timer);host.removeEventListener('click',click);host.removeEventListener('change',change);host.removeEventListener('input',input);};
}
